### ISSUE TITLE
puso fails puso

### ISSUE THREAD

**Issue by AlbertUnruh** [mache102/puso#1]
[puso.py](https://github.com/mache102/puso/blob/3d0673d5afcb318d3ddfd2e604bae27c64cc9bdb/puso.py) isn't compatible with puso!

This should be fixed if you want to be consistent ;)

**Comment by mache102** [comment]
sorry, I'm not sure what you mean, do you have a screenshot?  it works just fine for me

**Comment by AlbertUnruh** [comment]
I mean there aren't any semicolons in the code ;)

**Comment by mache102** [comment]
> I mean there aren't any semicolons in the code ;)

ahaha.... *looks at new features* yeah, this is gonna be one heck of a mess.

**Comment by mache102** [comment]
might as well as add that to my todo list though :)
1. PyPi
2. puso compatible code
