### ISSUE TITLE
README.md doesn't list one-liner enforcing as current feature

### ISSUE THREAD

**Issue by mybearworld** [mache102/puso#11]
README.md doesn't list one-liner enforcing as current feature.

**Comment by mache102** [comment]
2023-04-15
- Resolved forced semicolon for implicit line breaks
- Patched `__import__` bypass for verbose imports
**- Added one-liner enforcing**

this line, unless you mean smth else?

**Comment by mybearworld** [comment]
```md
# Current Features:
- Semicolon Enforcing
- Verbose Imports
```
Shouldn't it also say One Line Enforcing here?

**Comment by mache102** [comment]
Ah, uhh.... not sure how I missed that lol. thanks
